# This file was generated by GoReleaser. DO NOT EDIT.
cask "statable" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "3171b6b5ee11eb4c3b5b075258e8bfef10b64b5c2762928f5778eea84ee5284e"
      url "https://github.com/key-arg/statable-cli/releases/download/v#{version}/statable_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d73d90ad8f0d6d89fa7dbe5de5fe64d83f4cd92e470ec8e3d70951332f633ce8"
      url "https://github.com/key-arg/statable-cli/releases/download/v#{version}/statable_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9f8fc48262539ac6189f3e0161d52c8374c8588b21fec75267a63c292f01d2ac"
      url "https://github.com/key-arg/statable-cli/releases/download/v#{version}/statable_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8927fea4f0df6cabb0ceca4c527933abf22ff2d740eb6039962f4c911a9153ed"
      url "https://github.com/key-arg/statable-cli/releases/download/v#{version}/statable_#{version}_linux_amd64.tar.gz"
    end
  end

  name "statable"
  desc "Read your Statable analytics from a terminal, a script, or CI"
  homepage "https://statable.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "statable"
  manpage "manpages/statable-api-call.1"
  manpage "manpages/statable-api-describe.1"
  manpage "manpages/statable-api-search.1"
  manpage "manpages/statable-api.1"
  manpage "manpages/statable-auth-login.1"
  manpage "manpages/statable-auth-logout.1"
  manpage "manpages/statable-auth-register.1"
  manpage "manpages/statable-auth-status.1"
  manpage "manpages/statable-auth.1"
  manpage "manpages/statable-check.1"
  manpage "manpages/statable-funnel.1"
  manpage "manpages/statable-funnels-create.1"
  manpage "manpages/statable-funnels-delete.1"
  manpage "manpages/statable-funnels-edit.1"
  manpage "manpages/statable-funnels.1"
  manpage "manpages/statable-goals-create.1"
  manpage "manpages/statable-goals-delete.1"
  manpage "manpages/statable-goals-edit.1"
  manpage "manpages/statable-goals.1"
  manpage "manpages/statable-keys-create.1"
  manpage "manpages/statable-keys-events.1"
  manpage "manpages/statable-keys-revoke.1"
  manpage "manpages/statable-keys-rotate.1"
  manpage "manpages/statable-keys.1"
  manpage "manpages/statable-now.1"
  manpage "manpages/statable-props.1"
  manpage "manpages/statable-query.1"
  manpage "manpages/statable-series.1"
  manpage "manpages/statable-settings-set-blocked-ips.1"
  manpage "manpages/statable-settings-set-countries.1"
  manpage "manpages/statable-settings-set-hostnames.1"
  manpage "manpages/statable-settings-set-public-dashboard.1"
  manpage "manpages/statable-settings-set-tracking.1"
  manpage "manpages/statable-settings-set.1"
  manpage "manpages/statable-settings.1"
  manpage "manpages/statable-sites-create.1"
  manpage "manpages/statable-sites-delete.1"
  manpage "manpages/statable-sites-edit.1"
  manpage "manpages/statable-sites-use.1"
  manpage "manpages/statable-sites.1"
  manpage "manpages/statable-snippet.1"
  manpage "manpages/statable-stats.1"
  manpage "manpages/statable-subscription.1"
  manpage "manpages/statable-top.1"
  manpage "manpages/statable-version.1"
  manpage "manpages/statable.1"
  bash_completion "completions/statable.bash"
  fish_completion "completions/statable.fish"
  zsh_completion "completions/statable.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/statable"]
    end
  end

  # No zap stanza required
end
