# This file was generated by GoReleaser. DO NOT EDIT.
cask "statable" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "fcd81127066356ef07b5f0989e71b0a22fe4df7ff7218e693fa57a2f2114b013"
      url "https://github.com/key-arg/statable-cli/releases/download/v#{version}/statable_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "31236b6a2e715d2c4d2c89d0f64a4041e1f72c01964fa7cdf4f007f0bee55e9f"
      url "https://github.com/key-arg/statable-cli/releases/download/v#{version}/statable_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1ba194e9e17e2b3a962499b361d6c48432feecfa494b85de3f97e43ba7441af7"
      url "https://github.com/key-arg/statable-cli/releases/download/v#{version}/statable_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "abd9231a5beaa57b9e462e0e0e913ba700a5a11abec255870fc0a9fcf2311694"
      url "https://github.com/key-arg/statable-cli/releases/download/v#{version}/statable_#{version}_linux_amd64.tar.gz"
    end
  end

  name "statable"
  desc "Read your Statable analytics from a terminal, a script, or CI"
  homepage "https://statable.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "statable"
  manpage "manpages/statable-api-call.1"
  manpage "manpages/statable-api-describe.1"
  manpage "manpages/statable-api-search.1"
  manpage "manpages/statable-api.1"
  manpage "manpages/statable-auth-login.1"
  manpage "manpages/statable-auth-logout.1"
  manpage "manpages/statable-auth-status.1"
  manpage "manpages/statable-auth.1"
  manpage "manpages/statable-check.1"
  manpage "manpages/statable-funnel.1"
  manpage "manpages/statable-funnels.1"
  manpage "manpages/statable-goals.1"
  manpage "manpages/statable-now.1"
  manpage "manpages/statable-props.1"
  manpage "manpages/statable-query.1"
  manpage "manpages/statable-series.1"
  manpage "manpages/statable-sites-use.1"
  manpage "manpages/statable-sites.1"
  manpage "manpages/statable-snippet.1"
  manpage "manpages/statable-stats.1"
  manpage "manpages/statable-subscription.1"
  manpage "manpages/statable-top.1"
  manpage "manpages/statable-version.1"
  manpage "manpages/statable.1"
  bash_completion "completions/statable.bash"
  fish_completion "completions/statable.fish"
  zsh_completion "completions/statable.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/statable"]
    end
  end

  # No zap stanza required
end
